// <auto-generated />
using System;
using MYPM.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MYPM.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430054658_ModifyLongToInt")]
    partial class ModifyLongToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MYPM.Data.Models.ArabianOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cuff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hata")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Mohori")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Ness")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rakaba")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tira")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("ArabianOrders");
                });

            modelBuilder.Entity("MYPM.Data.Models.NewOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DueAmount")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaidAmount")
                        .HasColumnType("integer");

                    b.Property<string>("SL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MYPM.Data.Models.PanjabiOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cuff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hata")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Komor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Mohori")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rakaba")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sina")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("PanjabiOrders");
                });

            modelBuilder.Entity("MYPM.Data.Models.SelowerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hip")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Komor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Ness")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("SelowerOrders");
                });

            modelBuilder.Entity("MYPM.Data.Models.ArabianOrder", b =>
                {
                    b.HasOne("MYPM.Data.Models.NewOrderModel", "NewOrder")
                        .WithMany("ArabianOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewOrder");
                });

            modelBuilder.Entity("MYPM.Data.Models.PanjabiOrder", b =>
                {
                    b.HasOne("MYPM.Data.Models.NewOrderModel", "NewOrder")
                        .WithMany("PanjabiOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewOrder");
                });

            modelBuilder.Entity("MYPM.Data.Models.SelowerOrder", b =>
                {
                    b.HasOne("MYPM.Data.Models.NewOrderModel", "NewOrder")
                        .WithMany("SelowerOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewOrder");
                });

            modelBuilder.Entity("MYPM.Data.Models.NewOrderModel", b =>
                {
                    b.Navigation("ArabianOrders");

                    b.Navigation("PanjabiOrders");

                    b.Navigation("SelowerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
